unifi_artifact_directory: '{{ inventory_dir }}/.cache/unifi-artifacts'
unifi_seed_directory: '{{ inventory_dir }}/.cache/unifi-seed/{{ unifi_vm_allocation.name
  }}'
unifi_backup_file: '{{ inventory_dir }}/.cache/unifi-backup/authoritative.unf'
