---
- name: 'fortigate_backup: backup'
  hosts: fortigates
  gather_facts: false
  become: false
  serial: 1
  vars_files:
  - "{{ vault_file | default(((playbook_dir ~ '/..') | realpath) ~ '/secrets/vault.yml') }}"
  roles:
  - role: fortigate_backup
    fortigate_backup_options:
      task_action: backup
