---
- name: 'cisco_switch: explicit action'
  hosts: cisco_switches
  gather_facts: false
  become: true
  serial: 1
  become_method: enable
  vars_files:
  - "{{ vault_file | default(((playbook_dir ~ '/..') | realpath) ~ '/secrets/vault.yml') }}"
  roles:
  - role: cisco_switch
