---
- name: 'opnsense_install: install'
  hosts: proxmox_hosts
  gather_facts: false
  become: false
  serial: 1
  roles:
  - role: opnsense_install
    opnsense_install_options:
      task_action: install
