---
- name: Prepare the controller's trusted Fortinet hostname
  hosts: fortigates
  gather_facts: false
  become: false
  serial: 1
  vars:
    ansible_connection: ansible.builtin.local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    ansible_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
    ansible_password: ''
  roles:
    - role: fortigate_controller
      fortigate_controller_options:
        task_action: prepare
