---
- name: 'proxmox_installer: prepare'
  hosts: proxmox_hosts
  gather_facts: false
  become: false
  serial: 1
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    ansible_connection: local
  vars_files:
  - "{{ vault_file | default(((playbook_dir ~ '/..') | realpath) ~ '/secrets/vault.yml') }}"
  roles:
  - role: proxmox_installer
    proxmox_installer_options:
      task_action: prepare
