---
- name: 'idrac_iso: status'
  hosts: idracs
  gather_facts: false
  become: false
  serial: 1
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    ansible_connection: local
  vars_files:
  - "{{ vault_file | default(((playbook_dir ~ '/..') | realpath) ~ '/secrets/vault.yml') }}"
  roles:
  - role: idrac_iso
    idrac_iso_options:
      task_action: status
    idrac_iso_manage_hosts: false
