---
- name: Verify guest initiated DEV egress and network isolation
  hosts: fedora_hosts
  gather_facts: false
  become: true
  roles:
    - role: fedora_host
      fedora_host_options: {task_action: connectivity}
